store:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: bookstore
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: ${ALIYUN_ACCESS_KEY}
    access-key-secret: ${ALIYUN_SECRET_KEY}
    bucket-name: ptu-bookstore

  redis:
    host: localhost
    port: 6379
    database: 10

  alipay:
    appid: 9021000161635489
    merchantPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCcN1/D8Mks8en+Jp/s+Vfr3BcmkRkkX8+QKZtohr6+qNId0NiNqfPXM9EcAFCXWis0dBB2ZZ1KbuIIUYROxUh7XOR2JB8sv7KqhL1uuCVtleGqMRoNP5zfz5qLTTwYtGAHkZoFhj4MPHz4/fpL/eDGccJwRgPhMU1soMMObH7q+f4+uBr8C1uYd6ujge3Jh2C450mlsQL84BEW4/bScfBeSk30IVMf+tBJynOhN6Tnzesri25Eksyo4bAN5mE8E8DGNFrSgdC8Gyh6YOgBaVPSEE9lUywQKeZ4pg/j8MAgvQYRxObqI4ZNFxEqzgNOJ8brkQC6JRDwSyqn3lH1W0sxAgMBAAECggEAIKHIlWuk+oiGMprq6VukrBZLl7jToa+J8jlex1TuX3Fwgt3vfpgz4Y5nbgv6ycMCJ3DfR3wugS/sc4RjuPipDWv4JV2iTXy127zivVAmMWAPxbeAE6hoIrCBPfwiQ57aOHqHzAOgznmMOY8ES/96hrmYvk9B3DaqT7i9RjQPxxGhCcLE2ciBomhKGeytSIZcFRsvxEwYbbFv+OMaLTt3mPG5XyMTnMVqOz9m4ooppEwO+rmJzjiNyKx86l5jI6TiRyjh3iV2iSYgrk1m4QI901bCMLY6DaT+OAOTtHDQZD5Z+IvH6AMT82U8G1R4tChioK7xPyP5bID3UmCPiUvGgQKBgQDrfpu8veRG/7F9Q5OHrivwiZWh4f/W1o5CQCtZNHvjW65cjx3r5noj6GB3/MIdfringcQ++CfDZG0rRxBNs3DFdI3gl87L/dapoGpupQNeYAa0MXZviYGMjCwyZa0wCnp7DM9grVXRVqNIGVfuxLU+fay//cGIy+xJnRn2RGv2WQKBgQCp0ZR77X5rWL9da1xn4SuOMHRiGUPNdTwygKUJLALml9iZYJd90RnrAyyIc+6pqO4CH+BOrmXzJCybYy3v5DC6Pi5LH78pHx65oq9H1hNT2YxwULCEDhlppm4zqVaokFsJJrxLaXCx4xg0BTiFGQqVuTjtQi59GarEG2l6lfuQmQKBgQC2g8zeDmpjIH8GL56i1LmXVnrTGV54updM/4DZRVUTVBYiBIXTNDDLrak+tXYY+ALTSD658wiWZjo6BXy8S+uGDZx8SgvrjBOYKgzzLg8bUN9BPuik73SpYmZKtQTyK9zbi4UaT50ofrZUBdhh5LD3+t0te9VIWYwLTag2drcaGQKBgQCmqkpQVoX8VN17kiLe0N8ubd/LZ4Bj5OtvpVJT7h3qspyh62rC0LXfMP5D7YQOfv0YmLBMiF0GhDpDRtOO3SX1o5FLqZyzfxdomYHtvuy5Hon2sTqMYEoQpocBrPCf/w1ZreqfGJzB+V+HrpgKCMmaqG52bL2zib1POpgK96guAQKBgQCrbE9WObqa57ZuO4mhdCwM9fRd68/JDViFU7IwmG8mnoTnkoVIjUB6uhHsRt4duZzw/LRTusi9G75sYMvsDZIOACG7M9CUM4Em9O7aeg4qvSgyh0aVFxWVbEWR9CrngXwrAOK4thqvMBFDu615o7qFz1U37d1oOmYL8I2zjMh/dw==
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgGZFpVvb1UkzAOoCZDpwxPufA9TsyyCtJaLhtTx+nMmw5RB+1P2M4TXJSqQ/+9JoyT5wgZ99YxrppOyhyr4rc1FzV9ExuoMhlBLtp0ayPiceaIcYYEWBSuBgLNSQXXNVcUIVr7n83++u4/6VUJjCtuzVNdhw4WACxBa+YgkeyY2cGR6E/i5fDpjiA5idETr2f/cvdby9jYNq69sA4etSjEIRNbHrWLIwirJFYNv2wouXFdlujYqj8MwnYNDuMIwCmsnLorn3iV7qtZxtjNR7U47LIXfLa4AzZhMc2w66PHoBGItU6V7yX4BINd528mUsXGIgB7W2LTkTQWnbfrP9PQIDAQAB
    notifyUrl: https://h6q9j1cdjz.fy.takin.cc/api/alipay/notify
    returnUrl: http://member.zyz.com/memberOrder.html
    signType: RSA2
    charset: utf-8
    gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

