store:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: book_store
    username: root
    password: 123456

#  alioss:
#    endpoint: oss-cn-beijing.aliyuncs.com
#    access-key-id: ${ALIYUN_ACCESS_KEY}
#    access-key-secret: ${ALIYUN_SECRET_KEY}
#    bucket-name: store-lunxi

  redis:
    host: localhost
    port: 6379
    database: 10

